"""
Django settings for gfvgbo project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import locale
import os


from .mysecrets import *

"""
example mysecrets.py file:

DB_NAME="........"
DB_USERNAME="........"
DB_PWD="........"
DB_HOSTNAME="....."

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True (set to False in production)

ALLOWED_HOSTS = ['*'] (set to list of allowed hosts in production)

SECRET_KEY = "................................"

BOT_NAME = "..."

NSS_HOST = 'ip address of nss server'  # leave empty string if no NSS server
NSS_PORT = nss_server_port_number

SOLR_HOST = 'hostname of apache solr instance' # leave empty string if no Apache Solr instance 
SOLR_PORT = 8983

SMTP_SERVER = ""
SMTP_USER = ""
SMTP_PASSWORD = ""
EMAIL_SENDER = "email address of sender"
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECRET_KEY is imported from secrets.py


INSTALLED_APPS = [
    'backoffice.apps.BackofficeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.postgres',
    'haystack',
    'ckeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gfvgbo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gfvgbo.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_NAME,
        'USER': DB_USERNAME,
        'PASSWORD': DB_PWD,
        'HOST': 'localhost',
        'PORT': '3306',
        'AUTOCOMMIT': True,
        'OPTIONS': {'charset': 'utf8mb4',
                    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"},
        # https://code.djangoproject.com/ticket/18392
    }
}

# https://django-haystack.readthedocs.io/en/master/tutorial.html#xapian
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'xapian_backend.XapianEngine',
        'PATH': '/opt/media/dclavorofvgbot/xapian/xapian_index',
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'it-IT'
# setup locale for whole application
locale.setlocale(locale.LC_ALL, 'it_IT.UTF-8')
TIME_ZONE = 'Europe/Rome'

USE_I18N = True
# USE_L10N = True # deprecated

USE_TZ = True

DATE_FORMAT = "%m/%d/%Y"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')


# MEDIA_ROOT is defined in secrets.py
#MEDIA_ROOT = '/opt/media/dclavorofvg-bot/'
# MEDIA_URL = '/media/'



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = '/opt/media/dclavorofvgot/media/'
MEDIA_URL = '/media/'


AUDIO_ROOT = os.path.join(MEDIA_ROOT, 'audio/')

# CKEDITOR_UPLOAD_PATH = 'uploads/'

# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar': 'full',
#         'format_tags' : 'b;strong;i;em;u;ins;s;strike;del;a[!href];code;pre'
#     },
# }


# number of columns of textareas
TEXT_AREA_COLUMNS = 60
